#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/make_metadata make_metadata /usr/bin/python3-make_metadata 200
	update-alternatives --install /usr/bin/mdexport mdexport /usr/bin/python3-mdexport 200
	update-alternatives --install /usr/bin/parse_xsd2 parse_xsd2 /usr/bin/python3-parse_xsd2 200
	update-alternatives --install /usr/bin/merge_metadata merge_metadata /usr/bin/python3-merge_metadata 200
fi

#DEBHELPER#

exit 0
