#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/make_metadata make_metadata /usr/bin/python2-make_metadata 300
	update-alternatives --install /usr/bin/mdexport mdexport /usr/bin/python2-mdexport 300
	update-alternatives --install /usr/bin/parse_xsd2 parse_xsd2 /usr/bin/python2-parse_xsd2 300
	update-alternatives --install /usr/bin/merge_metadata merge_metadata /usr/bin/python2-merge_metadata 300
fi

#DEBHELPER#

exit 0
